### ISSUE TITLE
Wrong time in docker container

### ISSUE THREAD

**Issue by reload81** [nilsramsperger/docker-nodebb#11]
Hello, the docker image works really well. Thank you very much for this.

However, I have the problem that the time in the docker container does not match the time outside. A change of the time is invalid after restarting the container again. The time differs by one hour. I assume that the time zone is not set correctly. Can you help me to change this setting?

**Comment by nilsramsperger** [comment]
An interesting problem. I never thought about that. :)
I just built a new "latest" image. Now you can give a timezone on creation of the container by setting "-e TIMEZONE=x".
The readme is updated accordingly.

**Comment by nilsramsperger** [comment]
It is now "-e timezone=x"

**Comment by reload81** [comment]
Thank you very much. I have fixed the problem myself in the meantime but for everyone else this is a good workaround.
