### ISSUE TITLE
Email notifications use port in their links

### ISSUE THREAD

**Issue by kelteseth** [nilsramsperger/docker-nodebb#12]
Email notification like post reply attach the port like this: https://forum.screen-play.app:4567/post/201 resulting in broken links

I'm not sure if this is because of my wrong configured  nginx from your comment here: https://github.com/nilsramsperger/docker-nodebb/issues/5

Also, this docker container email did only work after using an external email server. Not sure if I did something wrong here.

Cheers!

**Comment by nilsramsperger** [comment]
What did you put into the "-e url=" parameter on container creation?

**Comment by kelteseth** [comment]
@nilsramsperger thank you looks like I missed that. 🎁

**Comment by nilsramsperger** [comment]
I updated the Readme to give a more prominent hint about this issue.
