### ISSUE TITLE
Mail is not always sent

### ISSUE THREAD

**Issue by reload81** [nilsramsperger/docker-nodebb#13]
it's me again :-)

I have the problem that emails are not always sent. The test succeeds, but after some time I get the error message "write EPIPE". Then when new users sign up they don't get a confirmation email.

My mail provider is Ionos (1&1) and I use the default mail option.

Do you know how I fix the problem?

**Comment by nilsramsperger** [comment]
Sounds like an internal NodeBB problem, or one at the receiving end. Hard to tell. May be, that's a case for the NodeBB support forum: [NodeBB Community](https://community.nodebb.org/)
Back in the days, when I hosted a NodeBB forum, I had quite some problems with mailing as well. My solution was to use the `nodebb-plugin-emailer-local` plugin and connect it to MailJet via API. That worked like a charm.

**Comment by nilsramsperger** [comment]
Closed due to inactivity.
