### ISSUE TITLE
SMTP does not functional

### ISSUE THREAD

**Issue by Vast-Stars** [nilsramsperger/docker-nodebb#4]
can't get any test mail from nodebb by using SMTP of outlook or gmail.

Is it because the ports in the container are not forwarded to the outside?

**Comment by nilsramsperger** [comment]
Usually Docker doesn't limit access to the internet from a container. At least you don't have to open outgoing ports on container creation. So your SMTP requests should not be blocked. 

That leaves several potential places where things might have gone wrong:
- I don't know how your NodeBB instance tries to send the SMTP requests. On my instance I am using the `nodebb-plugin-emailer-local` plugin. It works like a charm.
- May be your Docker host has a firewall confiuration that blocks outgoing SMTP.
- Another chance would be the receiver blocking incomming SMTP.
