### ISSUE TITLE
NodeBB 1.13 

### ISSUE THREAD

**Issue by kelteseth** [nilsramsperger/docker-nodebb#5]
So the new version was just released. 

https://github.com/NodeBB/NodeBB/releases/tag/v1.13.0

Cheers

**Comment by kelteseth** [comment]
So I successfuly upgraded my nodebb instance to 1.13. Thanks for this quick update! Maybe we should add `docker pull nilsramsperger/nodebb` before recreating the docker container before upgrading 😂

Also I created a short guide on how to add reverse proxy with lets encrypt into my readme. If you want you can copy the steps :) https://gitlab.com/kelteseth/ScreenPlayProject#nodebb-forum-setup

Cheers

**Comment by nilsramsperger** [comment]
Thanks for the feedback. I allways try to push the updates asap. :)

I did a short review of your HTTPS guide, and found a flaw. You are using published ports to connect NodeBB and Nginx. That way the NodeBB container is accessible via http://forum.screen-play.app:4567 without HTTPS.
To prevent that, use a docker internal network to connect the containers.

Without going into detail, you should do the following steps:
1) Create an internal network: `docker network create myNetwork`
2) Remove the `-p` Part from the NodeBB start command
3) Add `—net myNetwork` To the NodeBB start command
4) Attach the Nginx to the internal network by: `docker network connect myNetwork myNginx`
5) In Nginx site config address the NodeBB via `http://myNodeBB.myNetwork:4567`

Greetings
Nils

**Comment by nilsramsperger** [comment]
Closed due to inactivity.
