### ISSUE TITLE
Didn't see files in folder linked with nodebb-* volumes

### ISSUE THREAD

**Issue by j0x3n** [nilsramsperger/docker-nodebb#6]
I used command line below:
`docker create --name cf --init --restart always -p 4567:4567 -v nodebb-data:/home/cf/data -v nodebb-files:/home/cf/file -v nodebb-config:/home/cf/config nilsramsperger/nodebb`
The site was installed, but there's no config.json in /home/cf/config

**Comment by nilsramsperger** [comment]
When mounting Volumes into Docker containers via `-v x:y` Parameter, the part after the : describes the location within the container and must not be changed. The part before the : points to the Docker volume or a path on the host`s file system.
I guess that you want to store the NodeBB data in your host’s filesystem. In that case try `-v /home/cf/config:/etc/nodebb` for the configuration. This maps your local directory `/home/cf/config` to the container’s `/etc/nodebb`  Set the other `-v` Parameters accordingly.

**Comment by j0x3n** [comment]
it's okay now, thanks~
