### ISSUE TITLE
Update github release

### ISSUE THREAD

**Issue by kelteseth** [nilsramsperger/docker-nodebb#9]
Just update to 1.15.2 without any issues, thanks! Maybe create a github release so other people get a notification of the update <3

**Comment by nilsramsperger** [comment]
I dropped that task a while ago, since I guess that not every Docker/DockerHub user of the image is following the repo here. Therefore I startet to publish new releases on my Twitter (@nilsramsperger). 
Anyway, I just created a release here. I hope to remember for future releases.
